### PR TITLE
Exclude buffers matching on `buftype`

### PR DESCRIPTION
**Pull request by I60R**
- quickfix
- help
- terminal
- prompt

### CODE REVIEW

**Comment by kaplanz** [comment]
Thanks for the contribution!

Just a brief point of discussion, should we consider adding this as a configurable option? I can't imagine why users would want Retrail enabled in a quickfix buffer (and I'm under the impression that `buftype` is only set to help when using `:help`), nevertheless, who knows what users may want.

I completely agree that if we add that as an option we should at least disable over those `buftype`s as the default. What do you think?

**Comment by I60R** [comment]
>nevertheless, who knows what users may want.

There would be really few users who want retrail being enabled in a quickfix buffer :smile: 

---

Anyway, this PR first of all fixes retrail being enabled in terminal window

**Comment by kaplanz** [comment]
Thanks for all the work into this! I've just been finishing up exams so I'm sorry it's taken a while to review these changes. I finish later this week, and will do a full review then.

**Comment by kaplanz** [comment]
Sorry this took to long to get around to! There were a few bugs I had to sort out (see [here](https://github.com/kaplanz/nvim-retrail/blob/719c64e96507419f1a3bba98cfb84c3b576f0201/lua/retrail/init.lua#L85) and [here](https://github.com/kaplanz/nvim-retrail/blob/719c64e96507419f1a3bba98cfb84c3b576f0201/lua/retrail/init.lua#L90), where `filetype` and `buftype` were accidentally swapped). Please let me know if there's any issues with this feature on your end.

Thanks a ton for your PR and work on this! I've made sure to mark you as the author on these commits.

**Pull request closed without merging**
