### PR TITLE
feat: exclude common plugins by default

### PR DESCRIPTION
**Pull request by pogopaule**
- feat: add WhichKey, alpha and mason.nvim to exclude table
- docs: sync README.md with default config

### CODE REVIEW

**Comment by pogopaule** [comment]
In my view it is reasonable to assume that you don't want to see whitespace for any of these three plugins.
Not everybody knows how to figure out the name of the buffer. E.g. in case of which-key it took me a moment to figure out the correct name.

**Comment by kaplanz** [comment]
> In my view it is reasonable to assume that you don't want to see whitespace for any of these three plugins.

I agree it likely does make sense to exclude other common plugins, the question I came across when I initially published this was which ones to include.

> Not everybody knows how to figure out the name of the buffer. E.g. in case of which-key it took me a moment to figure out the correct name.

It's funny you mention that, since I actually just added which-key to my own exclude table as well. Before merging this we should consider what other common plugins are worth including, that way there's a bit more consistency to the defaults.

**Comment by kaplanz** [comment]
For reference, in my current configuration I include telescope as well:

```lua
require("retrail").setup {
  filetype = {
    exclude = {
      "",
      "checkhealth",
      "diff",
      "help",
      "man",
      "mason.nvim",
      "TelescopePrompt",
      "WhichKey",
    },
  },
}
```

Since I don't have edit permission for your fork, could you add `TelescopePrompt` to this PR as well? (And if it's not a hassle, also alphabetize the entries?)

**Comment by pogopaule** [comment]
> could you add `TelescopePrompt` to this PR as well? (And if it's not a hassle, also alphabetize the entries?)

done

> Before merging this we should consider what other common plugins are worth including, that way there's a bit more consistency to the defaults.

Good idea. I have quite a few plugins installed and so far this exclude list looks good to me. I have used retrail a few days while developing and haven't come across other plugins that need to be excluded.

**Comment by kaplanz** [comment]
Thank you @pogopaule for taking the time to do this!

**Pull request merged**
