### PR TITLE
feat: exclude `toggleterm` by default

### LINKED ISSUE #12: Whitespace is shown when using a terminal
Thanks for the plugin. It's working well.

However, when I have a neovim terminal open (via plugin [toggleterm](https://github.com/akinsho/toggleterm.nvim)) the retrail plugin highlights whitespace. When I disable the retrail plugin completely the highlighting goes away. I believe my configuration is saying to exclude retrail when I'm using a terminal.

My configuration includes:

``` lua
  buftype = {
    -- Strictly enable only on `include`ed buftypes. When false, only disabled
    -- on an `exclude`ed buftype.
    strict = false,
    -- Included filetype list. Overrides `include` list.
    include = {},
    -- Excluded filetype list.
    exclude = {
      "help",
      "nofile",
      "prompt",
      "quickfix",
      "terminal",
    }
  },
```

### PR DESCRIPTION
**Pull request by azzamsa**
Fixes #12

### CODE REVIEW

**Comment by kaplanz** [comment]
Just a quick comment before I merge, could you double check why there are so many lines changed in defaults.lua? This should only be a single insertion in that file. (Perhaps you changed the line endings?)

Otherwise looks good!

**Comment by azzamsa** [comment]
Oh, My! I don't see the git changes before committing. Because the git gutter doesn't show anything.
Yes, I assume it comes from `stevearc/conform.nvim`.

**Comment by kaplanz** [comment]
Gotcha! Could I ask you to quickly fix that then I'll merge?

**Comment by kaplanz** [comment]
Merged, thanks!

**Comment by azzamsa** [comment]
Thank you! :tada:

**Pull request merged**
